### PR TITLE
upgraded to webpack 4 & babel 7 rest of dependancies also updated to …

### PR DESCRIPTION
**Pull request by tbrnslv**
…latest versions. All tests are passing.

### CODE REVIEW

**Review by donskov — APPROVED** [review]

**Comment by donskov** [comment]
@tbrnslv Thanks for your work! I updated package to version `2.0.0` and now you can use it (https://github.com/donskov/static-render-html-webpack-plugin/releases/tag/2.0.0)

**Comment by tbrnslv** [comment]
Hello,
No problem... I really needed something to make pure non virtual-dom html
from jsx files with webpack. I also added some code from
https://www.npmjs.com/package/webpack-watch-files-plugin in newest commit
you can check it out on my fork. Now it can also refresh on change in other
components, not just entry. I can refactor it little more, as for now this
is little to hacky for my taste and I can make another pull request to your
repo when I do it.
Best regards,
Branislav

**Comment by donskov** [comment]
@tbrnslv I think it's a good idea to add a listener for files and refresh bundle. Need to do research and use the best variant for this. Also, I have plans to add eslint, plugin using examples, maybe typescript to package. I will be glad of your help

**Comment by tbrnslv** [comment]
I fixed and added importing without caching for list of files, so it works,
it's just not elegant. I am still newbie with webpack plugins. Anyway, I
really like the project, so I will try to help out with implementing some
of those stuff. I use eslint a lot and I am trying to do most of my project
with typescript lately, so I will definitely help out when I have some free
time. Regards!

**Comment by donskov** [comment]
@tbrnslv Today I added some [improvements](https://github.com/donskov/static-render-html-webpack-plugin/pull/7) for package: eslint and files structure. If you create PR I will be grateful to you. Thanks!

**Pull request merged**
